# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\computer vision\Homework\Hw1\training\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import showDataset
import showHyperpar
import showPlt
import showStruct


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 411, 281))
        self.groupBox.setObjectName("groupBox")
        self.showImage = QtWidgets.QPushButton(self.groupBox)
        self.showImage.setGeometry(QtCore.QRect(20, 20, 371, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.showImage.setFont(font)
        self.showImage.setObjectName("showImage")
        self.showImage.clicked.connect(showDataset.showData)
        self.showHm = QtWidgets.QPushButton(self.groupBox)
        self.showHm.setGeometry(QtCore.QRect(20, 60, 371, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.showHm.setFont(font)
        self.showHm.setObjectName("showHm")
        self.showHm.clicked.connect(showHyperpar.showHyper)
        self.showShortcut = QtWidgets.QPushButton(self.groupBox)
        self.showShortcut.setGeometry(QtCore.QRect(20, 100, 371, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.showShortcut.setFont(font)
        self.showShortcut.setObjectName("showShortcut")
        self.showShortcut.clicked.connect(showStruct.showStr)
        self.showAccur = QtWidgets.QPushButton(self.groupBox)
        self.showAccur.setGeometry(QtCore.QRect(20, 140, 371, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.showAccur.setFont(font)
        self.showAccur.setObjectName("showAccur")
        self.showAccur.clicked.connect(showPlt.showplt)
        self.test = QtWidgets.QPushButton(self.groupBox)
        self.test.setGeometry(QtCore.QRect(20, 220, 371, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.test.setFont(font)
        self.test.setObjectName("test")
        self.test.clicked.connect(self.testdata)
        self.getNum = QtWidgets.QLineEdit(self.groupBox)
        self.getNum.setGeometry(QtCore.QRect(20, 180, 371, 26))
        self.getNum.setObjectName("getNum")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "VGG16 Test"))
        self.showImage.setText(_translate("MainWindow", "1. Show Train Images"))
        self.showHm.setText(_translate("MainWindow", "2. Show HyperParameter"))
        self.showShortcut.setText(_translate("MainWindow", "3. Show Model Shortcut"))
        self.showAccur.setText(_translate("MainWindow", "4. Show Accuracy"))
        self.test.setText(_translate("MainWindow", "5. Test"))

    def testdata(self):
        idx = self.getNum.text()
        import loadModel
        loadModel.runTest(idx)

